### ISSUE TITLE
Add link in README.md to CONTRIBUTING.md

### ISSUE THREAD

**Issue by gfda** [opentok-community/insights-api-samples#5]
Would it be a good idea to create a section in the README with a link to CONTRIBUTING?

I would like to work on that.

**Comment by michaeljolley** [comment]
What do you suggest adding @gfda?

**Comment by gfda** [comment]
We could change the Getting Help (README.md) section by adding something like:

## Getting Help

- Read and follow all guidelines on [CONTRIBUTING.md](<link-to-file>)

**Comment by gfda** [comment]
What do you think?

**Comment by michaeljolley** [comment]
I like that you're wanting to contribute, but I think that's probably not needed.

**Comment by gfda** [comment]
Ok, Thanks @MichaelJolley for clarifying this.
